version: '3.8'

services:
  mysql-usuario:
    image: mysql:latest
    container_name: mysql-usuario-container
    ports:
      - "3307:3306"
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=123
      - MYSQL_DATABASE=db_usuario
      - MYSQL_ROOT_PASSWORD=123
    networks:
      - ms-usuario
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "admin", "-p123"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s

  mysql-sala:
    image: mysql:latest
    container_name: mysql-sala-container
    ports:
      - "3308:3306"
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=123
      - MYSQL_DATABASE=db_sala
      - MYSQL_ROOT_PASSWORD=123
    networks:
      - ms-sala
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "admin", "-p123"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s

  mysql-reserva:
    image: mysql:latest
    container_name: mysql-reserva-container
    ports:
      - "3309:3306"
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=123
      - MYSQL_DATABASE=db_reserva
      - MYSQL_ROOT_PASSWORD=123
    networks:
      - ms-reserva
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "admin", "-p123"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s

  ms-usuario:
    build:
      context: ./ms-usuario
      dockerfile: Dockerfile
    container_name: ms-usuario-container
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-usuario:3306/db_usuario
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: 123
    depends_on:
      mysql-usuario:
        condition: service_healthy 
    restart: always
    networks:
      - ms-usuario

  ms-sala:
    build:
      context: ./ms-sala
      dockerfile: Dockerfile
    container_name: ms-sala-container
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-sala:3306/db_sala
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: 123
    depends_on:
      mysql-sala:
        condition: service_healthy 
    restart: always
    networks:
      - ms-sala

  ms-reserva:
    build:
      context: ./ms-reserva
      dockerfile: Dockerfile
    container_name: ms-reserva-container
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-reserva:3306/db_reserva
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: 123
    depends_on:
      mysql-reserva:
        condition: service_healthy 
    restart: always
    networks:
      - ms-reserva

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-container
    ports:
      - "3000:3000"
    depends_on:
      - ms-usuario
      - ms-sala
      - ms-reserva
    networks:
      - ms-usuario
      - ms-sala
      - ms-reserva
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx-gateway
    command: /bin/bash -c "sleep 10 && nginx -g 'daemon off;'"
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend:/usr/share/nginx/html:ro
    depends_on:
      - ms-usuario
      - ms-sala
      - ms-reserva
      - frontend
    networks:
      - ms-usuario
      - ms-sala
      - ms-reserva
    restart: always
    
  adminer:
    image: adminer
    ports:
      - "4040:8080"
    networks:
      - ms-usuario
      - ms-sala
      - ms-reserva
  
  rabbitmq:
    image: rabbitmq:3.7.8-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "admin"
    networks:
      - ms-usuario
      - ms-sala
      - ms-reserva

networks:
  ms-usuario:
  ms-sala:
  ms-reserva: