version: "3.8"

services:
  postgres_user:
    image: postgres:15
    container_name: postgres_user
    restart: always
    environment:
      POSTGRES_DB: admin  
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    networks:
      - reservas-salas
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  postgres_room:
    image: postgres:15
    container_name: postgres_room
    restart: always
    environment:
      POSTGRES_DB: admin 
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5434:5432"
    networks:
      - reservas-salas
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  postgres_reserve:
    image: postgres:15
    container_name: postgres_reserve
    restart: always
    environment:
      POSTGRES_DB: admin
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5435:5432"
    networks:
      - reservas-salas
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  user-service:
    build: ./user-service
    container_name: user-service
    restart: always
    depends_on:
      postgres_user:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_user:5432/admin
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_OPEN_IN_VIEW: "false"
    ports:
      - "8091:8080"
    networks:
      - reservas-salas
  room-service:
    build: ./room-service
    container_name: room-service
    restart: always
    depends_on:
      postgres_room:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_room:5432/admin
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_OPEN_IN_VIEW: "false"
    ports:
      - "8092:8080"
    networks:
      - reservas-salas
  reserve-service:
    build: ./reserve-service
    container_name: reserve-service
    restart: always
    depends_on:
      postgres_reserve:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_reserve:5432/admin
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_OPEN_IN_VIEW: "false"
    ports:
      - "8093:8080"
    networks:
      - reservas-salas
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "8080:80"
    networks:
      - reservas-salas

networks:
  reservas-salas: